apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-deployment
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-cont
        image: abdullah77044/mern_application-frontend:latest
        ports:
        - containerPort: 80

